# yaml-language-server: $schema=https://raw.githubusercontent.com/mfontanini/presenterm/master/config-file-schema.json

defaults:
  validate_overflows: always
  max_columns: 100
  max_rows_alignment: center
  max_rows: 50

transition:
  # how long the transition should last.
  duration_millis: 500

  # how many frames should be rendered during the transition
  frames: 45

  # the animation to use
  animation:
    style: slide_horizontal
